from datetime import date
from typing import Optional, Protocol, runtime_checkable
from lawboi.domain.models import Act, ActVersion, Provision
from lawboi.domain.dto import RetrievedProvision


@runtime_checkable
class StructuredStore(Protocol):
    # write side (ingest)
    def upsert_act(self, act: Act) -> int: ...
    def upsert_act_version(self, version: ActVersion) -> int: ...
    def insert_provision(self, provision: Provision) -> int: ...
    def version_has_provisions(self, act_version_id: int) -> bool: ...
    def ingested_global_ids(self) -> set[int]: ...

    # read side (retrieval)
    def fts_search(self, query: str, effective_date: date) -> list[RetrievedProvision]: ...
    def exact_lookup(self, section_num: str, as_of: date, limit: int,
                     eli: Optional[str], title_query: Optional[str]) -> list[RetrievedProvision]: ...

    # read side (acts API)
    def get_act(self, eli: str) -> Optional[Act]: ...
    def list_act_versions(self, eli: str) -> list[ActVersion]: ...
    def provisions_as_of(self, eli: str, on: date) -> list[Provision]: ...
