from datetime import date
from typing import Optional, Protocol, runtime_checkable
from lawboi.domain.models import Act, ActVersion, Provision
from lawboi.domain.dto import RetrievedProvision


@runtime_checkable
class StructuredStore(Protocol):
    # write side (ingest)
    async def upsert_act(self, act: Act) -> int: ...
    async def upsert_act_version(self, version: ActVersion) -> int: ...
    async def insert_provision(self, provision: Provision) -> int: ...
    async def version_fully_indexed(self, act_version_id: int) -> bool: ...
    async def delete_provisions_for_version(self, act_version_id: int) -> None: ...
    async def ingested_global_ids(self) -> set[int]: ...

    # read side (retrieval)
    async def fts_search(self, query: str, effective_date: date) -> list[RetrievedProvision]: ...
    async def exact_lookup(self, section_num: str, as_of: date, limit: int,
                     eli: Optional[str], title_query: Optional[str]) -> list[RetrievedProvision]: ...

    # read side (acts API)
    async def get_act(self, eli: str) -> Optional[Act]: ...
    async def list_act_versions(self, eli: str) -> list[ActVersion]: ...
    async def provisions_as_of(self, eli: str, on: date) -> list[Provision]: ...

    # conversation history
    async def create_conversation(self) -> int: ...
    async def append_message(self, conversation_id: int, role: str, content: str) -> None: ...
    async def recent_messages(self, conversation_id: int, limit: int = 10) -> list[dict]: ...
